### ISSUE TITLE
严重bug&浏览器调试时出现跨域请求

### ISSUE THREAD

**Issue by jeffreys-cat** [airingursb/sunnybaby#1]
bug：点击添加城市按钮后返回主界面会显示两份城市列表。在浏览器中调试出现了跨域请求，导致完全没法调试。。加个白名单？

**Comment by airingursb** [comment]
@HuJian21 谢谢反馈！
两份城市列表的bug，我待会修复一下。
跨域问题推荐使用Chrome浏览器，安装Allow-Control-Allow-Origin插件，即可解决。

**Comment by jeffreys-cat** [comment]
Ok

**Comment by airingursb** [comment]
@HuJian21 
Bug已修复，在PageWillEnter的时候要提前清空数组。

**Comment by jeffreys-cat** [comment]
@airingursb 嗯，我拉下来
