### ISSUE TITLE
我想问问,webApp怎么打包成安卓和ios?求指导

### ISSUE THREAD

**Issue by Niofh** [airingursb/sunnybaby#3]
你现在项目是Ionic +angular2,但只能通过网址去访问,但是我想通过手机图标打开,应该怎么做呢?

**Comment by airingursb** [comment]
@598220654 具体可见官方文档，这里指出了如何在真机上install ionic项目 [http://ionicframework.com/docs/v2/getting-started/installation/](http://ionicframework.com/docs/v2/getting-started/installation/)
